services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  web:
    image: nginx:latest

  db:
    image: "mysql:latest"
    # environment:
    #   MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    #   MYSQL_DATABASE: "${MYSQL_DATABASE}"
    env_file:
      - mysql.config.env